# Generated by Django 4.0.4 on 2022-04-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_user_message_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
    ]
